import { Knex } from 'knex';

// We need to fill the up and down methods with the SQL queries Knex will run
// when running migrations and rolling them back.

export async function up(knex: Knex): Promise<void> {
  return knex.raw(`
  CREATE TABLE products (
      id serial PRIMARY KEY NOT NULL, 
      name VARCHAR(50) NOT NULL, 
      price NUMERIC(8,2),
      stock integer
      )
  `);
}
// CREATE TABLE products (
//   id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//   name text NOT NULL,
//   description text NOT NULL

export async function down(knex: Knex): Promise<void> {
  return knex.raw(`
    DROP TABLE products
  `);
}
// todo: update postgres values to be working so I can resolve the error and make the migration
// todo: create stuff in the db
